format = """
[░▒▓](#BFBBB0)\
[  ](bg:#BFBBB0 fg:#1F2224)\
[](bg:#B3AFA4 fg:#BFBBB0)\
$directory\
[](fg:#B3AFA4 bg:#73706A)\
$git_branch\
$git_status\
[](fg:#73706A bg:#33322F)\
$nodejs\
$rust\
$golang\
$php\
[](fg:#33322F bg:#1F2224)\
$time\
[ ](fg:#1F2224)\
\n$character"""

[directory]
style = "fg:#FFF8EB bg:#B3AFA4"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#73706A"
format = '[[ $symbol $branch ](fg:#B3AFA4 bg:#73706A)]($style)'

[git_status]
style = "bg:#73706A"
format = '[[($all_status$ahead_behind )](fg:#B3AFA4 bg:#73706A)]($style)'

[nodejs]
symbol = ""
style = "bg:#33322F"
format = '[[ $symbol ($version) ](fg:#B3AFA4 bg:#33322F)]($style)'

[rust]
symbol = ""
style = "bg:#33322F"
format = '[[ $symbol ($version) ](fg:#B3AFA4 bg:#33322F)]($style)'

[golang]
symbol = "ﳑ"
style = "bg:#33322F"
format = '[[ $symbol ($version) ](fg:#B3AFA4 bg:#33322F)]($style)'

[php]
symbol = ""
style = "bg:#33322F"
format = '[[ $symbol ($version) ](fg:#B3AFA4 bg:#33322F)]($style)'

[time]
disabled = true
time_format = "%R" # Hour:Minute Format
style = "bg:#1F2224"
format = '[[  $time ](fg:#BFBBB0 bg:#1F2224)]($style)'